# Generated by Django 5.2.9 on 2026-07-15 02:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(db_index=True, max_length=64)),
                ('action_payload', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=255)),
                ('requested_by', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('executing', 'Executing'), ('done', 'Done'), ('failed', 'Failed'), ('declined', 'Declined'), ('timed_out', 'Timed out')], db_index=True, default='pending', max_length=16)),
                ('auto_approved', models.BooleanField(default=False)),
                ('diff_fingerprint', models.CharField(blank=True, max_length=128)),
                ('decided_by', models.CharField(blank=True, max_length=128)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('executing_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='agent_actio_status_1423bd_idx'), models.Index(fields=['action_type', '-created_at'], name='agent_actio_action__15d684_idx')],
            },
        ),
    ]
